#ifndef _BOARD_H_
#define _BOARD_H_

#define VALVE_PIN_IO GPIO_NUM_3
#define PUMP_PIN_IO GPIO_NUM_4
#define PEDAL_PIN_IO GPIO_NUM_15
#define BOOT_PIN_IO GPIO_NUM_9
#define LDO_12V_ENABLE_PIN_IO GPIO_NUM_0

#define BUTTON_UP_PIN_IO GPIO_NUM_1
#define BUTTON_DOWN_PIN_IO GPIO_NUM_1
#define BUTTON_LEFT_PIN_IO GPIO_NUM_1
#define BUTTON_RIGHT_PIN_IO GPIO_NUM_1
#define BUTTON_SELECT_PIN_IO GPIO_NUM_1
#define BUTTON_POWER_PIN_IO GPIO_NUM_1

#endif // _BOARD_H_